//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLibrary.databaseAPPLM
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string CATEGORY_BOOK { get; set; }
        public string AUTHOR { get; set; }
        public int YEAR_RELEASEED { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
    }
}
